FROM centos:centos8.2.2004

# ENV PIP_INSTALL_ARG="--default-timeout=100 --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple"
ENV PIP_INSTALL_ARG="--default-timeout=100 --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple"
# ENV PIP_INSTALL_ARG="--no-cache-dir"

RUN yum update -y \
    && yum install -y sudo \
    && sudo yum install -y wget gcc gcc-c++ make python3-devel llvm llvm-devel git-all tk-devel \
    tcl-devel sqlite-devel gdbm-devel xz-devel readline-devel python3-tkinter net-tools firewalld \
    && yum clean all

RUN sudo yum install python36 -y \
    && sudo wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz \
    && tar -xzf ta-lib-0.4.0-src.tar.gz \
    && cd ta-lib/ \
    && ./configure --prefix=/usr \
    && make \
    && sudo make install \
    && cd .. \
    && pip3 --version \
    && pip3 install --upgrade pip $PIP_INSTALL_ARG \
    && pip3 install TA-Lib==0.4.17 $PIP_INSTALL_ARG \
    && rm -r ta-lib \
    && rm ta-lib-0.4.0-src.tar.gz \
    && pip3 --version


RUN pip3 install numpy==1.16.2 $PIP_INSTALL_ARG \
    && pip3 install empyrical==0.5.3 $PIP_INSTALL_ARG \
    && pip3 install matplotlib==3.3.2 $PIP_INSTALL_ARG \
    && pip3 install seaborn==0.9.0 $PIP_INSTALL_ARG \
    && pip3 install mplfinance==0.12.6a3 $PIP_INSTALL_ARG \
    && pip3 install abupy==0.4.0 $PIP_INSTALL_ARG \
    && pip3 install TA-Lib==0.4.17 $PIP_INSTALL_ARG \
    && pip3 install peakutils==1.3.3 $PIP_INSTALL_ARG \
    && pip3 install ipywidgets==7.4.2 $PIP_INSTALL_ARG \
    && pip3 install bokeh==2.0.2 $PIP_INSTALL_ARG \
    && pip3 install toolz==0.10.0 $PIP_INSTALL_ARG \
    && pip3 install notebook $PIP_INSTALL_ARG \
    && pip3 install jupyter_contrib_nbextensions $PIP_INSTALL_ARG \
    && pip3 install quantaxis==1.9.30 $PIP_INSTALL_ARG \
    && pip3 install pandas==1.0.5 $PIP_INSTALL_ARG \
    && pip3 uninstall -y pytdx janus \
    && pip3 install pytdx==1.72 janus==0.4.0 $PIP_INSTALL_ARG \
    # 启用jupyter扩展
    && jupyter contrib nbextension install --user \
    && pip3 install --upgrade git+https://github.com/GuQiangJS/gquant.git --no-cache-dir

EXPOSE 8888

CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0","--allow-root"]